### PR TITLE
Fix bug causing infinite loop in non-terminated code chunks

### LINKED ISSUE #9: Add guardrails against infinite loops in cases of invalid code
At present, if we have `.qmd` files with things like incomplete code sections, we'd expect to get stuck in an infinite loop somewhere

### PR DESCRIPTION
**Pull request by thisisnic**
Fixes #9

### CODE REVIEW

File: tests/testthat/test-infinite-loop-bug.R [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+  expect_error(
+    qmdparse::parse_qmd(tf),
+    regexp = "terminator not found"
+  )
+
+})
+
+
+
+
```
Comment (thisisnic) [inline tests/testthat/test-infinite-loop-bug.R]:
```suggestion
```
